theme: jekyll-theme-slate
title: 7th Annual training course on Viral Bioinformatics and Genomics (24 - 28 June 2024)
description: McCall computer cluster, Garscube campus, University of Glasgow, United Kingdom